print("please enter the first name")
n1 = input()
print("please input their GPA")
g1 = int(input())
print("please enter the second name")
n2 = input()
print("please input their GPA")
g2 = int(input())
print("please enter the third name")
n3 = input()
print("please input their GPA")
g3 = int(input())
print("please enter the fourth name")
n4 = input()
print("please input their GPA")
g4 = int(input())
average = float((g1+g2+g3+g4))/4
print(n1, n2, n3, "and", n4, "have an average GPA of", average)